//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForm.Properties {
    using System;
    using System.Drawing;

    internal class Resources {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoginForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // Resources from ProjectDB.Properties.Resources
        internal static Bitmap RawImage4 {
            get {
                object obj = ResourceManager.GetObject("RawImage4", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        // Resources from LoginForm.Properties.Resources
        internal static Bitmap GYM_APP {
            get {
                object obj = ResourceManager.GetObject("GYM_APP", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap GYM_APP1 {
            get {
                object obj = ResourceManager.GetObject("GYM_APP1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap sa {
            get {
                object obj = ResourceManager.GetObject("sa", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap WhatsApp_Image_2024_05_04_at_11_53_36_574ba208 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2024-05-04 at 11.53.36_574ba208", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
